# Generated by Django 6.0.3 on 2026-03-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('customer', '0002_review_customer_re_product_906588_idx'),
        ('seller', '0002_remove_attribute_seller_attr_subcate_144b20_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_status', 'Order Status Update'), ('seller_verification', 'Seller Verification Update'), ('general', 'General Notification')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='seller_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.sellerprofile'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx'),
        ),
    ]
