# Generated by Django 6.0.3 on 2026-03-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_notification_type_notification_order_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_notific_cbfe88_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='seller_profile',
        ),
    ]
