# Generated by Django 6.0.3 on 2026-03-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_notification_core_notifi_notific_cbfe88_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_images/'),
        ),
    ]
