# Generated by Django 6.0.3 on 2026-04-12 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('is_cancellable', models.BooleanField(default=True)),
                ('is_returnable', models.BooleanField(default=True)),
                ('return_days', models.IntegerField(default=7)),
                ('approval_status', models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, help_text='Admin remarks for product approval/rejection', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.subcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('mrp', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('stock_quantity', models.IntegerField()),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('tax_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='seller.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seller.productvariant')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField()),
                ('reason', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_changes', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='seller.productvariant')),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_slug', models.SlugField(unique=True)),
                ('gst_number', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=50, null=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('business_address', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=10)),
                ('admin_remarks', models.TextField(blank=True, help_text='Admin remarks for seller verification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_image', models.ImageField(upload_to='sellerprofile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.sellerprofile'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku_code'], name='seller_prod_sku_cod_437a57_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='seller_prod_product_f6b790_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['created_at'], name='seller_prod_created_e880eb_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['stock_quantity'], name='seller_prod_stock_q_14d479_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['variant'], name='seller_prod_variant_7979f6_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['is_primary'], name='seller_prod_is_prim_e6fc95_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['variant'], name='seller_inve_variant_bc5a41_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['created_at'], name='seller_inve_created_319f58_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['performed_by'], name='seller_inve_perform_0f1e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['verification_status'], name='seller_sell_verific_c43e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['created_at'], name='seller_sell_created_72eea6_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['store_slug'], name='seller_sell_store_s_f81622_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['approval_status'], name='seller_prod_approva_28e580_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'approval_status'], name='seller_prod_seller__ea7734_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory', 'is_active'], name='seller_prod_subcate_0abcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='seller_prod_slug_57edeb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='seller_prod_created_ecc8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='seller_prod_is_acti_379088_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['review_count'], name='seller_prod_review__0ff97b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-review_count', '-created_at'], name='seller_prod_review__ca4557_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('slug', 'seller')},
        ),
    ]
