# Generated by Django 6.0.3 on 2026-03-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attribute',
            name='seller_attr_subcate_144b20_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='attributeoption',
            name='seller_attr_attribu_62d0bd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='variantattributebridge',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='variantattributebridge',
            name='seller_vari_variant_cb59f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='variantattributebridge',
            name='seller_vari_option__162f7f_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['review_count'], name='seller_prod_review__0ff97b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-review_count', '-created_at'], name='seller_prod_review__ca4557_idx'),
        ),
        migrations.RemoveField(
            model_name='attributeoption',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='variantattributebridge',
            name='option',
        ),
        migrations.RemoveField(
            model_name='variantattributebridge',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeOption',
        ),
        migrations.DeleteModel(
            name='VariantAttributeBridge',
        ),
    ]
