# Generated by Django 6.0.3 on 2026-04-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('core', '0001_initial'),
        ('customer', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydiscountbridge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='categoryofferbridge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='deal',
            name='products',
            field=models.ManyToManyField(related_name='deals', to='seller.product'),
        ),
        migrations.AddField(
            model_name='categorydiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.discount'),
        ),
        migrations.AddField(
            model_name='categoryofferbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.offer'),
        ),
        migrations.AddField(
            model_name='offerdiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.discount'),
        ),
        migrations.AddField(
            model_name='offerdiscountbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.offer'),
        ),
        migrations.AddField(
            model_name='platformcommission',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.orderitem'),
        ),
        migrations.AddField(
            model_name='platformcommission',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerprofile'),
        ),
        migrations.AddField(
            model_name='productdiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.discount'),
        ),
        migrations.AddField(
            model_name='productdiscountbridge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AddField(
            model_name='productofferbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.offer'),
        ),
        migrations.AddField(
            model_name='productofferbridge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
    ]
