name: Django Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/StackShop-Project

            echo "Pull latest code"
            git pull origin main

            echo "Activate virtualenv"
            source venv/bin/activate

            echo "Install dependencies"
            pip install -r requirements.txt

            echo "Apply migrations"
            python manage.py makemigrations
          
            echo "Run migrations"
            python manage.py migrate

            echo "Collect static"
            python manage.py collectstatic --noinput

            echo "Restart Gunicorn"
            sudo systemctl restart gunicorn

            echo "Restart Nginx"
            sudo systemctl restart nginx
          EOF